[package]
name = "xq"
version = "0.1.0"
authors = ["mi_sawa <mi.sawa.1216+git@gmail.com>"]
edition = "2018"
description = "A reimplementation of jq."

[[bin]]
name = "xq"
path = "src/bin/main.rs"
required-features = ["build-binary"]

[features]
default = ["build-binary"]
build-binary = ["anyhow", "clap", "serde_json", "simplelog"]

[dependencies]
thiserror = "1.0.29"
log = "0.4.14"
nom = "7.0.0"
im-rc = "15.0.0"
sized-chunks = "0.6.5"
num = "0.4.0"
itertools = "0.10.1"
serde = "1.0.130"

serde_json = { version = "1.0.67", optional = true }
clap = { version = "3.0.0-beta.4", optional = true }
anyhow = { version = "1.0", optional = true }
simplelog = { version = "0.10.0", optional = true }
